### ISSUE TITLE
文字列を引数として渡すと、引数の文字列にhtmlエスケープを施した値を返り値として返す関数「h」の作成

### ISSUE THREAD

**Issue by kaoruueno** [kaoruueno/lamp_practice#3]
`function h($str) {
    return htmlspecialchars($str, ENT_QUOTES, UTF-8);
}`

**Comment by manatago** [comment]
まずはこのイシュー番号に即したブランチを作って、そこで作業しましょう。
git checkout develop
 でdevelopブランチに移動して、
git checkout -b issue/3
で新しいブランチを作成して移動します。

そこでmodelの中のfunctions.phpの最後に
function h($str){
  return htmlspecialchars($str,ENT_QUOTES,'UTF-8');
}
を追加して、
add してcommitしてpushの流れを進めましょう。
